Overview Exercises
For each of the following questions, formulate a null and alternative hypothesis (be as specific as you can be), then give an example of what a true positive, true negative, type I and type II errors would look like. Note that some of the questions are intentionally phrased in a vague way. It is your job to reword these as more precise questions that could be tested.

Define: - Null hypothesis - Alternative hypothesis

Give an example of: - True positive - True negative - Type I error - Type II error

- Has the network latency gone up since we switched internet service providers?
H
0
: the network latency is the same since the ISP switch.

H
a
: the new ISP has higher latency

True Positive: We reject 
H
0
, our latency is not the same since the switch

False Positive: We reject 
H
0
, we thought latency was not the same, however that was incorrect

False Negative: We fail to reject 
H
0
:Data showed that latency was higher and it was incorrect

True Negative: Data shows that latency is higher and it was correct

- Is the website redesign any good?
H
0
: the number of click throughs since the site redesign has remained the same

H
a
: there are more click throughs since the site redesign

True Positive: reject 
H
0
, we conclude that the redesign helped, and it really did

False Positive: reject 
H
0
, we conclude that the redesign helped, but really it didn't

False Negative: fail to reject 
H
0
, we conclude the redesign did not help, but really it did

True Negative: fail to reject 
H
0
, we conclude the redesign did not help, and it really didn't

### Comparison of groups

In [ ]:
# 1. Yes

In [6]:
# 2. State your null and alternative hypotheses.
#State your alpha.
#Performa chi test of independence.
# State your conclusion

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pip install pymysql

Note: you may need to restart the kernel to use updated packages.


In [7]:
import pymysql as pymy

In [8]:
import env4

In [20]:
from pydataset import data
from scipy import stats


In [10]:
mpg_df = data('mpg')
mpg_df.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [11]:
alpha = 0.5

In [18]:
observed = pd.crosstab(mpg_df.manufacturer, mpg_df["class"])
observed


class         2seater  compact  midsize  minivan  pickup  subcompact  suv
manufacturer                                                             
audi                0       15        3        0       0           0    0
chevrolet           5        0        5        0       0           0    9
dodge               0        0        0       11      19           0    7
ford                0        0        0        0       7           9    9
honda               0        0        0        0       0           9    0
hyundai             0        0        7        0       0           7    0
jeep                0        0        0        0       0           0    8
land rover          0        0        0        0       0           0    4
lincoln             0        0        0        0       0           0    3
mercury             0        0        0        0       0           0    4
nissan              0        2        7        0       0           0    4
pontiac             0        0        5        0       0           0    0
subaru              0        4        0        0       0           4    6
toyota              0       12        7        0       7           0    8
volkswagen          0       14        7        0       0           6    0

In [21]:
chi2, p, degf, expected = stats.chi2_contingency(observed)


In [22]:
# print 'Observed Values' followed by a new line
print('Observed Values\n')

# print the values from the 'observed' dataframe
print(observed.values)

# print --- and then a new line, 'Expected Values', followed by another new line
print('---\nExpected Values\n')

# print the expected values array
print(expected.astype(int))

# print a new line
print('---\n')

# print the chi2 value, formatted to a float with 4 digits. 
print(f'chi^2 = {chi2:.4f}') 

# print the p-value, formatted to a float with 4 digits. 
print(f'p     = {p:.4f}')


Observed Values

[[ 0 15  3  0  0  0  0]
 [ 5  0  5  0  0  0  9]
 [ 0  0  0 11 19  0  7]
 [ 0  0  0  0  7  9  9]
 [ 0  0  0  0  0  9  0]
 [ 0  0  7  0  0  7  0]
 [ 0  0  0  0  0  0  8]
 [ 0  0  0  0  0  0  4]
 [ 0  0  0  0  0  0  3]
 [ 0  0  0  0  0  0  4]
 [ 0  2  7  0  0  0  4]
 [ 0  0  5  0  0  0  0]
 [ 0  4  0  0  0  4  6]
 [ 0 12  7  0  7  0  8]
 [ 0 14  7  0  0  6  0]]
---
Expected Values

[[0 3 3 0 2 2 4]
 [0 3 3 0 2 2 5]
 [0 7 6 1 5 5 9]
 [0 5 4 1 3 3 6]
 [0 1 1 0 1 1 2]
 [0 2 2 0 1 2 3]
 [0 1 1 0 1 1 2]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 2 2 0 1 1 3]
 [0 1 0 0 0 0 1]
 [0 2 2 0 1 2 3]
 [0 6 5 1 4 5 9]
 [0 5 4 1 3 4 7]]
---

chi^2 = 464.3721
p     = 0.0000


In [23]:
if p < alpha:
    print('We reject the null hypothesis')
else:
    print('We fail to reject the null hypothesis')


We reject the null hypothesis


In [51]:
# 3. Use the data from the employees database to answer these questions:

# Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

# Is an employee's gender independent of whether or not they are or have been a manager?
sql_manager = ''' SELECT dept_name, gender , emp_no IN (SELECT emp_no FROM dept_manager) AS is_manager
FROM employees
JOIN dept_emp USING(emp_no)
JOIN departments USING(dept_no)
join dept_manager USING(emp_no)
WHERE dept_manager.to_date > now();
'''

In [26]:
sql_query = """
SELECT dept_name, gender FROM employees
JOIN dept_emp USING(emp_no)
JOIN departments USING(dept_no)
WHERE to_date > now()
"""

In [52]:
employees = pd.read_sql(sql_manager, env4.get_db_url('employees'))


In [48]:
employees.to_csv('employees.csv')
employees = pd.read_csv('employees.csv', index_col=0)
employees.head()


dept_name gender
0        Marketing      M
1          Finance      F
2  Human Resources      F
3       Production      M
4      Development      F

In [32]:
# Is an employee's gender independent of whether an employee works in sales or marketing? (only look at current employees)

gender_df = employees[employees.dept_name.isin(['Marketing', 'Sales'])]
gender_df.head()



dept_name gender
104290  Marketing      F
104291  Marketing      M
104292  Marketing      F
104293  Marketing      F
104294  Marketing      F

In [34]:
gender_observed = pd.crosstab(gender_df.dept_name, gender_df.gender)
gender_observed

gender         F      M
dept_name              
Marketing   5864   8978
Sales      14999  22702

In [36]:
chi2, p, degf, expected = stats.chi2_contingency(gender_observed)
p
# There exists some relationship between an employee's gender independent of whether an employee works in sales or marketing.

0.5691938610810126

In [38]:
#if p < alpha:
 #   print('We reject the null hypothesis')
#else:
 #   print('There exists some relationship between')

In [53]:
# Is an employee's gender independent of whether or not they are or have been a manager?

employees.to_csv('employees.csv')
employees = pd.read_csv('employees.csv', index_col=0)
employees.head()

dept_name gender  is_manager
0        Marketing      M           1
1          Finance      F           1
2  Human Resources      F           1
3       Production      M           1
4      Development      F           1

In [56]:
manager_observed = pd.crosstab(employees.gender, employees.is_manager)
manager_observed

is_manager  1
gender       
F           4
M           5

In [57]:
chi2, p, degf, expected = stats.chi2_contingency(manager_observed)
p
# We reject the null hypothesis that an employee's gender independent of whether or not they are or have been a manager?

1.0

### Correlation

In [59]:
# Answer with the type of stats test you would use (assume normal distribution):

telco_churn_query = """
SELECT *
FROM customers
JOIN internet_service_types USING(internet_service_type_id);
"""

In [62]:

charges = pd.read_sql(telco_churn_query, env4.get_db_url('telco_churn'))



In [68]:
pd.options.display.max_columns = 25

charges.to_csv('employees.csv')
charges = pd.read_csv('employees.csv', index_col=0)
charges.head()

internet_service_type_id customer_id  gender  senior_citizen partner  \
0                         1  0002-ORFBO  Female               0     Yes   
1                         1  0003-MKNFE    Male               0      No   
2                         2  0004-TLHLJ    Male               0      No   
3                         2  0011-IGKFF    Male               1     Yes   
4                         2  0013-EXCHZ  Female               1     Yes   

  dependents  tenure phone_service multiple_lines online_security  \
0        Yes       9           Yes             No              No   
1         No       9           Yes            Yes              No   
2         No       4           Yes             No              No   
3         No      13           Yes             No              No   
4         No       3           Yes             No              No   

  online_backup device_protection tech_support streaming_tv streaming_movies  \
0           Yes                No          Yes          Yes               No   
1            No                No           No           No              Yes   
2            No               Yes           No           No               No   
3           Yes               Yes           No          Yes              Yes   
4            No                No          Yes          Yes               No   

   contract_type_id paperless_billing  payment_type_id  monthly_charges  \
0                 2               Yes                2             65.6   
1                 1                No                2             59.9   
2                 1               Yes                1             73.9   
3                 1               Yes                1             98.0   
4                 1               Yes                2             83.9   

  total_charges churn internet_service_type  
0         593.3    No                   DSL  
1         542.4    No                   DSL  
2        280.85   Yes           Fiber optic  
3       1237.85   Yes           Fiber optic  
4         267.4   Yes           Fiber optic

In [78]:
#charges['total_charges'] = charges['total_charges'].apply(lambda x: x.astype('category'))
#charges['total_charges'] = charges['total_charges'].astype(float)


In [82]:
charges = charges[charges.total_charges != ""]


In [83]:
charges = charges[charges.total_charges != " "]

In [86]:
#charges = charges[charges['total_charges'].str.strip() != ""]
charges['total_charges'] = charges['total_charges'].astype(float)



In [89]:
charges.columns

Index(['internet_service_type_id', 'customer_id', 'gender', 'senior_citizen',
       'partner', 'dependents', 'tenure', 'phone_service', 'multiple_lines',
       'online_security', 'online_backup', 'device_protection', 'tech_support',
       'streaming_tv', 'streaming_movies', 'contract_type_id',
       'paperless_billing', 'payment_type_id', 'monthly_charges',
       'total_charges', 'churn', 'internet_service_type'],
      dtype='object')

In [127]:
alpha = 0.05

charges_observed = pd.crosstab(charges.tenure, charges.monthly_charges) 
charges_observed[:5]

monthly_charges  18.25   18.40   18.55   18.70   18.75   18.80   18.85   \
tenure                                                                    
1                     0       0       0       0       0       1       2   
2                     0       0       0       0       1       0       0   
3                     0       0       0       0       0       1       0   
4                     0       0       0       0       0       0       1   
5                     0       0       0       0       0       0       0   

monthly_charges  18.90   18.95   19.00   19.05   19.10   ...  117.15  117.20  \
tenure                                                   ...                   
1                     1       0       1       1       3  ...       0       0   
2                     0       0       0       0       0  ...       0       0   
3                     0       0       0       0       2  ...       0       0   
4                     0       0       2       0       0  ...       0       0   
5                     0       0       0       0       0  ...       0       0   

monthly_charges  117.35  117.45  117.50  117.60  117.80  118.20  118.35  \
tenure                                                                    
1                     0       0       0       0       0       0       0   
2                     0       0       0       0       0       0       0   
3                     0       0       0       0       0       0       0   
4                     0       0       0       0       0       0       0   
5                     0       0       0       0       0       0       0   

monthly_charges  118.60  118.65  118.75  
tenure                                   
1                     0       0       0  
2                     0       0       0  
3                     0       0       0  
4                     0       0       0  
5                     0       0       0  

[5 rows x 1584 columns]

In [ ]:
r, p = stats.pearsonr(charges.tenure, charges.monthly_charges)

In [93]:
r, p = stats.pearsonr(charges.tenure, charges.monthly_charges)
print(f'''
r = {r:.4f}
p = {p:.4f}
'''.strip())
if p < alpha:
    print("Reject our null hypothesis")
else:
    print("Fail to reject our null hypothesis")

r = 0.2469
p = 0.0000
Reject our null hypothesis


In [95]:
r, p = stats.pearsonr(charges.tenure, charges.total_charges)
print(f'''
r = {r:.4f}
p = {p:.4f}
'''.strip())
if p < alpha:
    print("Reject our null hypothesis")
else:
    print("Fail to reject our null hypothesis")

r = 0.8259
p = 0.0000
Reject our null hypothesis


In [ ]:
# 3. Use the employees database.

#Is there a relationship between how long an employee has been with the company and their salary?

#Is there a relationship between how long an employee has been with the company and the number of titles they have had?

In [131]:
titles_query = ''' select emp_no, hire_date, count(*) as n_titles
from titles 
join employees using(emp_no)    
group by emp_no; '''

In [148]:
salary_query = ''' select distinct(emp_no), DATEDIFF(curdate(), hire_date) as 'days', salary
from employees
join salaries using(emp_no)
join dept_emp using(emp_no)
WHERE dept_emp.to_date > now() 
'''

In [132]:
emp_titles = pd.read_sql(titles_query, env4.get_db_url('employees'))

#emp_salary = pd.read_sql(salary_query, env4.get_db_url('employees'))


In [133]:
pd.options.display.max_columns = 25

emp_titles.to_csv('employees.csv')
emp_titles = pd.read_csv('employees.csv', index_col=0)
emp_titles.head()

emp_no   hire_date  n_titles
0   10001  1986-06-26         1
1   10002  1985-11-21         1
2   10003  1986-08-28         1
3   10004  1986-12-01         2
4   10005  1989-09-12         2

In [134]:
emp_titles.dtypes

emp_no        int64
hire_date    object
n_titles      int64
dtype: object

In [126]:
alpha_ = 0.05

In [ ]:
#Creating a crosstab table for the observed data

charges_observed = pd.crosstab(charges.tenure, charges.monthly_charges) 
charges_observed[:5]

In [147]:
#emp_titles['hire_date'] = pd.to_datetime(emp_titles['hire_date'], errors='coerce')  #convert to date_time but may have lost values

# Convert hire_date to numerical representation
emp_titles['hire_date_numeric'] = emp_titles['hire_date'].apply(lambda x: x.timestamp())  #would choose this method first next time

#r, p = stats.pearsonr(emp_titles['hire_date_numeric'], emp_titles['n_titles'])


In [144]:
emp_titles.head()

emp_no  hire_date  n_titles  hire_date_numeric
0   10001 1986-06-26         1        520128000.0
1   10002 1985-11-21         1        501379200.0
2   10003 1986-08-28         1        525571200.0
3   10004 1986-12-01         2        533779200.0
4   10005 1989-09-12         2        621561600.0

In [145]:
#Using the pearsonr package to measure the linear relationship between two datasets.

r, p = stats.pearsonr(emp_titles.hire_date_numeric, emp_titles.n_titles)

#r, p = stats.pearsonr(df.tenure, df.n_titles)


In [146]:
#Defining the confidence in determining the hypothesis that best describes the results.

r, p = stats.pearsonr(charges.tenure, charges.monthly_charges)
print(f'''
r = {r:.4f}
p = {p:.4f}
'''.strip())
if p < alpha_:
    print("Reject our null hypothesis")
else:
    print("Fail to reject our null hypothesis")

r = 0.2469
p = 0.0000
Reject our null hypothesis


In [149]:
#Is there a relationship between how long an employee has been with the company and their salary?

emp_salary = pd.read_sql(salary_query, env4.get_db_url('employees'))


In [150]:
pd.options.display.max_columns = 25

emp_salary.to_csv('employees.csv')
emp_salary = pd.read_csv('employees.csv', index_col=0)
emp_salary.head()

emp_no   days  salary
0   10001  13655   60117
1   10001  13655   62102
2   10001  13655   66074
3   10001  13655   66596
4   10001  13655   66961

In [152]:
#r, p = stats.pearsonr(emp_salary.days, emp_salary.salary)

r, p = stats.pearsonr(emp_salary.days, emp_salary.salary)
print(f'''
r = {r:.4f}
p = {p:.4f}
'''.strip())
if p < alpha_:
    print("Reject our null hypothesis")
else:
    print("Fail to reject our null hypothesis")


r = 0.1633
p = 0.0000
Reject our null hypothesis


In [154]:
# 4. Is there a relationship between days and reaction time?

sleep = data('sleepstudy')
sleep.head()


Reaction  Days  Subject
1  249.5600     0      308
2  258.7047     1      308
3  250.8006     2      308
4  321.4398     3      308
5  356.8519     4      308

In [155]:
r, p = stats.pearsonr(sleep.Days, sleep.Reaction)
print(f'''
r = {r:.4f}
p = {p:.4f}
'''.strip())
if p < alpha_:
    print("Reject our null hypothesis")
else:
    print("Fail to reject our null hypothesis")

r = 0.5352
p = 0.0000
Reject our null hypothesis


### Comparison of Mean

In [ ]:
# 1. Answer with the type of test you would use (assume normal distribution):

#Is there a difference in grades of students on the second floor compared to grades of all students?
One Sample T-Test

#Are adults who drink milk taller than adults who don't drink milk?
Independent T-test aka Two Sample T-test

#Is the price of gas higher in Texas or in New Mexico? 
Anova
#Are there differences in stress levels between students who take data science vs students who take web development vs students who take cloud academy?
Anova

In [ ]:
# 2. Ace Realty wants to determine whether the average time it takes to sell homes is different for its two offices. 
# A sample of 40 sales from office #1 revealed a mean of 90 days and a standard deviation of 15 days. 
# A sample of 50 sales from office #2 revealed a mean of 100 days and a standard deviation of 20 days. Use a .05 level of significance.



In [ ]:
n1 = 40  #sample
x = 90  #mean
s1 = 15  #standard deviation

n2 = 50
x = 100
s2 = 20

t, p = stats.ttest_ind_from_stats(xbar1, s1, n1, xbar2, s2, n2)

single_p = p / 2
single_p

In [ ]:
# 3. Load the mpg dataset and use it to answer the following questions:
#Is there a difference in fuel-efficiency in cars from 2008 vs 1999?
#Are compact cars more fuel-efficient than the average car?
#Do manual cars get better gas mileage than automatic cars?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pydataset import data
from scipy import stats



In [2]:
#Is there a difference in fuel-efficiency in cars from 2008 vs 1999?
#Are compact cars more fuel-efficient than the average car?
#Do manual cars get better gas mileage than automatic cars?

mpg = data('mpg')
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [23]:
round(mpg.groupby('year')[['cty','hwy']].mean(),2)

#sales_data.groupby(‘month’).agg([sum, np.mean])[[‘purchase_amount’, 'year']] 

cty    hwy
year              
1999  17.02  23.43
2008  16.70  23.45

In [30]:
round(mpg.groupby('year')[['cty','hwy']].agg(['sum','mean']),2)


cty          hwy       
       sum   mean   sum   mean
year                          
1999  1991  17.02  2741  23.43
2008  1954  16.70  2744  23.45

In [47]:
# Filter the DataFrame for the year 2008
fuel_2008 = mpg[mpg['year'] == 2008]
fuel_1999 = mpg[mpg['year'] == 1999]

# Calculate the mean of the combined highway and city mileage for the year 2008
mean_combined_mileage_2008 = fuel_2008[['hwy', 'cty']].mean(axis=1)
mean_mileage_1999 = fuel_1999[['hwy', 'cty']].mean(axis=1)


In [50]:
alpha =0.5

In [57]:
t, p = stats.ttest_ind(mean_combined_mileage_2008, mean_mileage_1999)
p



0.8263744040323578

In [58]:
single_p = p / 2
single_p

0.4131872020161789

In [59]:
if p / 2 > alpha:
    print("We fail to reject the null hypothesis")
elif t < 0:
    print("We fail to reject the null hypothesis")
else:
    print("We reject the null hypothesis")


We fail to reject the null hypothesis


In [169]:
#Do manual cars get better gas mileage than automatic cars?

manual = mpg[mpg['trans'].str.startswith('manual')]
auto = mpg[mpg['trans'].str.startswith('auto')]

# Calculate the mean of the combined highway and city mileage for the year 2008
mean_trans = manual[['hwy', 'cty']].sum(axis=1).mean()
#mean_trans
#auto_trans = auto[['hwy', 'cty']].sum(axis=1).mean()


In [187]:
m_trans = manual[['hwy', 'cty']].mean(axis=1)
a_trans = auto[['hwy', 'cty']].mean(axis=1)

In [192]:
t, p = stats.ttest_ind(m_trans, a_trans)
t, p

(4.593437735750014, 7.154374401145685e-06)

In [193]:
formatted_p = f"{p:.6f}"
print(formatted_p)

0.000007


In [105]:
if p / 2 > alpha:
    print("We fail to reject the null hypothesis")
elif t < 0:
    print("We fail to reject the null hypothesis")
else:
    print("We reject the null hypothesis")


We reject the null hypothesis


In [60]:
mpg.head()

manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
1         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
2         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
3         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
4         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
5         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [120]:
#Are compact cars more fuel-efficient than the average car?

compact = mpg[mpg['class'] == 'compact']
mpg_avg = mpg['hwy'].mean() + mpg['cty'].mean()
mpg_avg  #population mean aka mu
mpg.hwy.mean()

40.299145299145295

In [149]:
mpg_overall = mpg[['hwy', 'cty']].sum(axis=1).mean()
mpg_overall

40.2991452991453

In [122]:
compact_avg = compact['hwy'].mean() + compact['cty'].mean()  #sample mean aka x
compact_avg

48.42553191489362

In [131]:
compct = compact[['hwy', 'cty']].mean(axis=1)
#compct

In [151]:

t, p = stats.ttest_1samp(compct, mpg_avg)
print('t=', t)
print('p=', p)

t= -31.264164803666866
p= 1.229360981374688e-32
